baseURL = "https://smeneguz.github.io/"
languageCode = "en"
title = "Silvio Meneguzzo"
copyright = "Silvio Meneguzzo"

[params]
  description = "PhD in Blockchain & DLT | Researcher at Links Foundation & University of Turin"
  author = "Silvio Meneguzzo"
  profileImage = "/images/silvio.jpeg"
  email = "meneguzzosilvio@gmail.com"
  googleScholar = "https://scholar.google.com/citations?user=cFT2URcAAAAJ"
  github = "https://github.com/smeneguz"
  linkedin = "https://www.linkedin.com/in/silvio-arras-meneguzzo"
  orcid = ""
  twitter = ""

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 4
  [[menu.main]]
    name = "Talks"
    url = "/talks/"
    weight = 5
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 6
  [[menu.main]]
    name = "Students"
    url = "/students/"
    weight = 7
  [[menu.main]]
    name = "Collaborate"
    url = "/collaborate/"
    weight = 8
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 9

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
